# Get Location Dictionary Columns
DICT_NAME = "name"
DICT_NAME_ID = "name_id"
DICT_ID = "id"

DICT_COUNTRY_NAME = f"country_{DICT_NAME}"
DICT_PROVINCE_NAME = f"province_{DICT_NAME}"
DICT_REGION_NAME = f"region_{DICT_NAME}"
DICT_CITY_NAME = f"city_{DICT_NAME}"
DICT_CITY_AREA_NAME = f"area_{DICT_NAME}"

DICT_COUNTRY_NAME_ID = f"country_{DICT_NAME_ID}"
DICT_PROVINCE_NAME_ID = f"province_{DICT_NAME_ID}"
DICT_REGION_NAME_ID = f"region_{DICT_NAME_ID}"
DICT_CITY_NAME_ID = f"city_{DICT_NAME_ID}"
DICT_CITY_AREA_NAME_ID = f"area_{DICT_NAME_ID}"

DICT_COUNTRY_ID = f"country_{DICT_ID}"
DICT_PROVINCE_ID = f"province_{DICT_ID}"
DICT_REGION_ID = f"region_{DICT_ID}"
DICT_CITY_ID = f"city_{DICT_ID}"
DICT_CITY_AREA_ID = f"area_{DICT_ID}"
