# Nomanitim GeoPy Debug Mode
LOCAL_DEBUG_MODE = False

# Local SQLite Databases Information
LOCAL_DATABASE_NAME = "nominatim.db"
LOCAL_TIMEOUT= 60

# Nomanitim GeoPy Location-related Table Names
LOCAL_NOMINATIM_ROWS_COUNTER_TABLE_NAME = "rows_counter"
LOCAL_NOMINATIM_COUNTRY_TABLE_NAME = "country"
LOCAL_NOMINATIM_REGION_TABLE_NAME = "region"
LOCAL_NOMINATIM_CITY_TABLE_NAME = "city"

LOCAL_NOMINATIM_ROOT_TABLE_NAME = LOCAL_NOMINATIM_COUNTRY_TABLE_NAME

LOCAL_NOMINATIM_CHILD_TABLE_NAMES = [
    LOCAL_NOMINATIM_REGION_TABLE_NAME,
    LOCAL_NOMINATIM_CITY_TABLE_NAME,
]

# Nomanitim GeoPy Location-related Table Columns
LOCAL_NOMINATIM_TABLE_NAME = "table_name"
LOCAL_NOMINATIM_COUNTER = "counter"
LOCAL_NOMINATIM_NAME = "name"
LOCAL_NOMINATIM_NAME_ID = "name_id"
LOCAL_NOMINATIM_SEARCH = "search"
LOCAL_NOMINATIM_ROWID = "rowid"

# Maximum Amount of Locations at its Nomanitim GeoPy Table
LOCAL_NOMINATIM_COUNTRY_MAX = 30
LOCAL_NOMINATIM_PROVINCE_MAX = 3 * LOCAL_NOMINATIM_COUNTRY_MAX
LOCAL_NOMINATIM_REGION_MAX = 2 * LOCAL_NOMINATIM_PROVINCE_MAX
LOCAL_NOMINATIM_CITY_MAX = 2 * LOCAL_NOMINATIM_REGION_MAX

# Times its Corresponding Location. Maximum Number of Searches for Given Table
LOCAL_NOMINATIM_LOCATION_SEARCH_MAX = 10
