from ..model.constants import (
    LOCATIONS_SCHEME_NAME,
    COUNTRIES_TABLE_NAME,
    REGIONS_TABLE_NAME,
    CITIES_TABLE_NAME,
    WAREHOUSES_TABLE_NAME,
    BRANCHES_TABLE_NAME,
)

# Action-related Commands
ADD = "add"
RM = "rm"
MOD = "mod"
GET = "get"
ALL = "all"
EXIT = "exit"

# Table-related Available Action Commands
ACTION_CMDS = [ADD, RM, MOD, GET, ALL, EXIT]

# Locations Scheme-related Commands
LOCATIONS_SCHEME_CMD = LOCATIONS_SCHEME_NAME
LOCATIONS_SCHEME_TABLE_CMDS = [
    COUNTRIES_TABLE_NAME,
    REGIONS_TABLE_NAME,
    CITIES_TABLE_NAME,
    WAREHOUSES_TABLE_NAME,
    BRANCHES_TABLE_NAME,
]

# Scheme Commands
SCHEME_CMDS = [LOCATIONS_SCHEME_CMD]

# ArgParse Commands
TABLE_ARGPARSE_CMDS = LOCATIONS_SCHEME_TABLE_CMDS
