# Matplotlib Graph File Names
RUSHWGRAPH_FILENAME = "rushcargo-warehouse-conns.png"
RUSHWGRAPH_DPI = 600
RUSHWGRAPH_ORIENTATION = "landscape"

# Matplotlib Graph Configurations
GRAPH_WITH_LABELS = True
GRAPH_WITH_ARROWS = True
GRAPH_NODE_SHAPE = "o"
GRAPH_LINE_WIDTHS = 2
GRAPH_FONT_SIZE = 14
GRAPH_FONT_COLOR = "whitesmoke"
GRAPH_FONT_WEIGHT = "bold"

# ... for Warehouse-related Nodes
GRAPH_REGION_MAIN_WAREHOUSE_NODE_COLOR = "#099268"
GRAPH_REGION_MAIN_WAREHOUSE_NODE_SIZE = 900
GRAPH_CITY_MAIN_WAREHOUSE_NODE_COLOR = "#20c997"
GRAPH_CITY_MAIN_WAREHOUSE_NODE_SIZE = 750
GRAPH_CITY_WAREHOUSE_NODE_COLOR = "#63e6be"
GRAPH_CITY_WAREHOUSE_NODE_SIZE = 600

# ... for Warehouse-related Edges
GRAPH_MAIN_REGION_WAREHOUSE_EDGE_COLOR = "#212529"
GRAPH_MAIN_REGION_WAREHOUSE_WIDTH = 8
GRAPH_MAIN_CITY_WAREHOUSE_EDGE_COLOR = "#343a40"
GRAPH_MAIN_CITY_WAREHOUSE_WIDTH = 6
GRAPH_CITY_WAREHOUSE_EDGE_COLOR = "#495057"
GRAPH_CITY_WAREHOUSE_WIDTH = 4

# Graph Node Types
GRAPH_REGION_MAIN_WAREHOUSE_NODE = "region-main"
GRAPH_CITY_MAIN_WAREHOUSE_NODE = "city-main"
GRAPH_CITY_WAREHOUSE_NODE = "city"
