# Data Directory
DATA_DIR = "data"

# Layouts Available for Plotting
LAYOUT_CIRCULAR = "circular"
LAYOUT_KAMADA = "kamada"
LAYOUT_SHELL = "shell"
LAYOUT_SPRING = "spring"
LAYOUT_CMDS = [LAYOUT_CIRCULAR, LAYOUT_KAMADA, LAYOUT_SHELL, LAYOUT_SPRING]

# Matplotlib Graph File Names
RUSHWGRAPH_FILENAME = "rushcargo-warehouses"

# Matplotlib RushWGraph Graph Configuration
RUSWGRAPH_BBOX = "tight"
RUSWGRAPH_TITLE = "Warehouses Graph"
RUSHWGRAPH_DPI = 900
RUSHWGRAPH_ORIENTATION = "landscape"

# Spring Layout Values
SPRING_DISTANCE = 50
SPRING_ITERATIONS = 200

# Matplotlib Graph Configurations
GRAPH_TRANSPARENT = False
GRAPH_WITH_LABELS = True
GRAPH_WITH_ARROWS = False
GRAPH_ARROW_SIZE = 10
GRAPH_NODE_SHAPE = "o"
GRAPH_FONT_SIZE = 4
GRAPH_FONT_COLOR = "#343a40"
GRAPH_FONT_WEIGHT = "bold"
GRAPH_FONT_ALPHA = 1
GRAPH_NODE_SIZE = 100
GRAPH_EDGE_WIDTH = 0.25

# ... for Warehouse-related Nodes
GRAPH_WAREHOUSE_NODE_EDGE_COLOR = "#343a40"

GRAPH_REGION_MAIN_WAREHOUSE_NODE_COLOR = "#38d9a9"
GRAPH_CITY_MAIN_WAREHOUSE_NODE_COLOR = "#96f2d7"
GRAPH_CITY_WAREHOUSE_NODE_COLOR = "#e6fcf5"

GRAPH_COUNTRY_WAREHOUSE_SIZE_FACTOR = 1
GRAPH_REGION_WAREHOUSE_SIZE_FACTOR = 1.5
GRAPH_CITY_WAREHOUSE_SIZE_FACTOR = 2

GRAPH_REGION_MAIN_WAREHOUSE_NODE_ALPHA = 1
GRAPH_CITY_MAIN_WAREHOUSE_NODE_ALPHA = 1
GRAPH_CITY_WAREHOUSE_NODE_ALPHA = 1

# ... for Warehouse-related Edges
GRAPH_WAREHOUSE_EDGE_COLOR = "#343a40"
GRAPH_WAREHOUSE_EDGE_ALPHA = 1

# Graph Node Types
GRAPH_REGION_MAIN_WAREHOUSE_NODE = "region-main"
GRAPH_CITY_MAIN_WAREHOUSE_NODE = "city-main"
GRAPH_CITY_WAREHOUSE_NODE = "city"
