# GeoPy Debug Mode
GEOPY_DEBUG_MODE = False

# Local SQLite Databases Information
GEOPY_DATABASE_NAME = "geopy.db"

# GeoPy Location-related Table Names
GEOPY_ROWS_COUNTER_TABLENAME = "rows_counter"
GEOPY_COUNTRY_TABLENAME = "country"
GEOPY_PROVINCE_TABLENAME = "province"
GEOPY_REGION_TABLENAME = "region"
GEOPY_CITY_TABLENAME = "city"
GEOPY_CITY_AREA_TABLENAME = "area"

GEOPY_ROOT_TABLENAME = GEOPY_COUNTRY_TABLENAME

GEOPY_CHILD_TABLENAMES = [
    GEOPY_PROVINCE_TABLENAME,
    GEOPY_REGION_TABLENAME,
    GEOPY_CITY_TABLENAME,
    GEOPY_CITY_AREA_TABLENAME,
]

# GeoPy Location-related Table Columns
GEOPY_TABLENAME = "tablename"
GEOPY_COUNTER = "counter"
GEOPY_NAME = "name"
GEOPY_NAME_ID = "name_id"
GEOPY_SEARCH = "search"
GEOPY_ROWID = "rowid"

# Maximum Amount of Locations at its GeoPy Table
GEOPY_COUNTRY_MAX = 30
GEOPY_PROVINCE_MAX = 3 * GEOPY_COUNTRY_MAX
GEOPY_REGION_MAX = 2 * GEOPY_PROVINCE_MAX
GEOPY_CITY_MAX = 2 * GEOPY_REGION_MAX
GEOPY_CITY_AREA_MAX = 3 * GEOPY_CITY_MAX

# Times its Corresponding Location. Maximum Number of Searches for Given Table
GEOPY_LOCATION_SEARCH_MAX = 10
