# Nomanitim GeoPy Debug Mode
NOMINATIM_DEBUG_MODE = False

# Local SQLite Databases Information
LOCAL_DATABASE_NAME = "geopy.db"
LOCAL_TIMEOUT= 60

# Nomanitim GeoPy Location-related Table Names
NOMINATIM_ROWS_COUNTER_TABLENAME = "rows_counter"
NOMINATIM_COUNTRY_TABLENAME = "country"
NOMINATIM_PROVINCE_TABLENAME = "province"
NOMINATIM_REGION_TABLENAME = "region"
NOMINATIM_CITY_TABLENAME = "city"

NOMINATIM_ROOT_TABLENAME = NOMINATIM_COUNTRY_TABLENAME

NOMINATIM_CHILD_TABLENAMES = [
    NOMINATIM_PROVINCE_TABLENAME,
    NOMINATIM_REGION_TABLENAME,
    NOMINATIM_CITY_TABLENAME,
]

# Nomanitim GeoPy Location-related Table Columns
NOMINATIM_TABLENAME = "tablename"
NOMINATIM_COUNTER = "counter"
NOMINATIM_NAME = "name"
NOMINATIM_NAME_ID = "name_id"
NOMINATIM_SEARCH = "search"
NOMINATIM_ROWID = "rowid"

# Maximum Amount of Locations at its Nomanitim GeoPy Table
NOMINATIM_COUNTRY_MAX = 30
NOMINATIM_PROVINCE_MAX = 3 * NOMINATIM_COUNTRY_MAX
NOMINATIM_REGION_MAX = 2 * NOMINATIM_PROVINCE_MAX
NOMINATIM_CITY_MAX = 2 * NOMINATIM_REGION_MAX

# Times its Corresponding Location. Maximum Number of Searches for Given Table
NOMINATIM_LOCATION_SEARCH_MAX = 10
